import React, { useEffect, useState } from "react";
import api from "../api";
export default function Workouts() {
  const [items,setItems]=useState([]); const [form,setForm]=useState({title:"",description:"",category:"Strength",difficulty:"Beginner",duration:30}); const [error,setError]=useState("");
  const load=()=>api.get("/workout").then(r=>setItems(r.data));
  useEffect(load,[]);
  const add=async e=>{e.preventDefault();setError("");try{await api.post("/workout",form);setForm({...form,title:"",description:""});load()}catch(err){setError(err.response?.data?.message||"Could not add workout")}};
  const del=async id=>{if(confirm("Delete this workout?")){await api.delete(`/workout/${id}`);load()}};
  return <main className="container py-4"><h2>Workout Management</h2><div className="row g-4"><div className="col-lg-5"><div className="card p-4"><h5>Add workout</h5>{error&&<div className="alert alert-danger">{error}</div>}<form onSubmit={add}><input className="form-control mb-2" placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><textarea className="form-control mb-2" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input className="form-control mb-2" type="text" placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><select className="form-select mb-2" value={form.difficulty} onChange={e=>setForm({...form,difficulty:e.target.value})}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select><input className="form-control mb-3" type="number" min="1" placeholder="Duration in minutes" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/><button className="btn btn-primary">Add Workout</button></form></div></div><div className="col-lg-7">{items.map(w=><div className="card p-4 mb-3" key={w._id}><div className="d-flex justify-content-between"><h5>{w.title}</h5><button className="btn btn-sm btn-outline-danger" onClick={()=>del(w._id)}>Delete</button></div><p>{w.description}</p><span className="badge text-bg-primary me-2">{w.category}</span><span className="badge text-bg-secondary">{w.difficulty} · {w.duration} min</span></div>)}</div></div></main>;
}
